"""1-letter and 3-letter amino-acid code maps.

Split out of ``biorazer.database.amino_acid`` (originally ``aa_list.py``).
The variants differ in the VALUE case only -- keys are always the standard
upper-case form. 1TO3 has 3 value forms (MET/met/Met), 3TO1 has 2 (M/m).
Use AMINO_ACIDS_1TO3_INITIAL_CAPITAL by default.
"""

AMINO_ACIDS_1LETTER = tuple("ACDEFGHIKLMNPQRSTVWY")
AMINO_ACIDS_3LETTER = (
    "ALA",
    "CYS",
    "ASP",
    "GLU",
    "PHE",
    "GLY",
    "HIS",
    "ILE",
    "LYS",
    "LEU",
    "MET",
    "ASN",
    "PRO",
    "GLN",
    "ARG",
    "SER",
    "THR",
    "VAL",
    "TRP",
    "TYR",
)

AMINO_ACIDS_1TO3_UPPER = {
    "A": "ALA",
    "C": "CYS",
    "D": "ASP",
    "E": "GLU",
    "F": "PHE",
    "G": "GLY",
    "H": "HIS",
    "I": "ILE",
    "K": "LYS",
    "L": "LEU",
    "M": "MET",
    "N": "ASN",
    "P": "PRO",
    "Q": "GLN",
    "R": "ARG",
    "S": "SER",
    "T": "THR",
    "V": "VAL",
    "W": "TRP",
    "Y": "TYR",
}

AMINO_ACIDS_1TO3_LOWER = {
    "A": "ala",
    "C": "cys",
    "D": "asp",
    "E": "glu",
    "F": "phe",
    "G": "gly",
    "H": "his",
    "I": "ile",
    "K": "lys",
    "L": "leu",
    "M": "met",
    "N": "asn",
    "P": "pro",
    "Q": "gln",
    "R": "arg",
    "S": "ser",
    "T": "thr",
    "V": "val",
    "W": "trp",
    "Y": "tyr",
}

AMINO_ACIDS_1TO3_INITIAL_CAPITAL = {
    "A": "Ala",
    "C": "Cys",
    "D": "Asp",
    "E": "Glu",
    "F": "Phe",
    "G": "Gly",
    "H": "His",
    "I": "Ile",
    "K": "Lys",
    "L": "Leu",
    "M": "Met",
    "N": "Asn",
    "P": "Pro",
    "Q": "Gln",
    "R": "Arg",
    "S": "Ser",
    "T": "Thr",
    "V": "Val",
    "W": "Trp",
    "Y": "Tyr",
}

AMINO_ACIDS_3TO1_UPPER = {
    "ALA": "A", "Ala": "A", "ala": "A",
    "CYS": "C", "Cys": "C", "cys": "C",
    "ASP": "D", "Asp": "D", "asp": "D",
    "GLU": "E", "Glu": "E", "glu": "E",
    "PHE": "F", "Phe": "F", "phe": "F",
    "GLY": "G", "Gly": "G", "gly": "G",
    "HIS": "H", "His": "H", "his": "H",
    "ILE": "I", "Ile": "I", "ile": "I",
    "LYS": "K", "Lys": "K", "lys": "K",
    "LEU": "L", "Leu": "L", "leu": "L",
    "MET": "M", "Met": "M", "met": "M",
    "ASN": "N", "Asn": "N", "asn": "N",
    "PRO": "P", "Pro": "P", "pro": "P",
    "GLN": "Q", "Gln": "Q", "gln": "Q",
    "ARG": "R", "Arg": "R", "arg": "R",
    "SER": "S", "Ser": "S", "ser": "S",
    "THR": "T", "Thr": "T", "thr": "T",
    "VAL": "V", "Val": "V", "val": "V",
    "TRP": "W", "Trp": "W", "trp": "W",
    "TYR": "Y", "Tyr": "Y", "tyr": "Y",
}

AMINO_ACIDS_3TO1_LOWER = {
    "ALA": "a", "Ala": "a", "ala": "a",
    "CYS": "c", "Cys": "c", "cys": "c",
    "ASP": "d", "Asp": "d", "asp": "d",
    "GLU": "e", "Glu": "e", "glu": "e",
    "PHE": "f", "Phe": "f", "phe": "f",
    "GLY": "g", "Gly": "g", "gly": "g",
    "HIS": "h", "His": "h", "his": "h",
    "ILE": "i", "Ile": "i", "ile": "i",
    "LYS": "k", "Lys": "k", "lys": "k",
    "LEU": "l", "Leu": "l", "leu": "l",
    "MET": "m", "Met": "m", "met": "m",
    "ASN": "n", "Asn": "n", "asn": "n",
    "PRO": "p", "Pro": "p", "pro": "p",
    "GLN": "q", "Gln": "q", "gln": "q",
    "ARG": "r", "Arg": "r", "arg": "r",
    "SER": "s", "Ser": "s", "ser": "s",
    "THR": "t", "Thr": "t", "thr": "t",
    "VAL": "v", "Val": "v", "val": "v",
    "TRP": "w", "Trp": "w", "trp": "w",
    "TYR": "y", "Tyr": "y", "tyr": "y",
}
